### PR TITLE
PatchInstaller refactor + index/integrity autogen

### PR DESCRIPTION
**Pull request by Soreepeong**
## Changes
1. Split out handlers for each commands into different files.
2. Added `index-update`: download the patch list, download the patch files if necessary, and create new patch index files from the latest resumable patch index file.
```
XIVLauncher.PatchInstaller.exe index-update ^
    C:\PATH_TO_PATCH_ROOT  ^
    -u <SE_username> ^
    -p <SE_password> ^
    -o <SE_OTP_if_any> ^
    --no-verify-old-patch-hash ^
    --no-verify-new-patch-hash
```
3. Added `index-create-integrity`: create and print `IntegrityCheckResult` in JSON format.
```
XIVLauncher.PatchInstaller.exe index-create-integrity ^
    C:\PATH_TO_PATCH_ROOT ^
    C:\PATH_TO_PATCH_ROOT\game\4e9a232b\D2023.10.23.0000.0000.patch.index ^
    C:\PATH_TO_PATCH_ROOT\game\ex1\6b936f08\D2023.10.23.0000.0000.patch.index ^
    C:\PATH_TO_PATCH_ROOT\game\ex2\f29a3eb2\D2023.10.23.0000.0000.patch.index ^
    C:\PATH_TO_PATCH_ROOT\game\ex3\859d0e24\D2023.10.23.0000.0000.patch.index ^
    C:\PATH_TO_PATCH_ROOT\game\ex4\1bf99b87\D2023.10.23.0000.0000.patch.index
```

## Confirmed stuff
* `index-create-integrity` results the exact same file for `2023.10.23.0000.0000`.
* `index-update` worked across 6.50 and 6.51.
* `index-create`, `index-verify`, and `index-repair` still work. (Mostly for debug purposes)
* `install` still works.

## Non-confirmed stuff
* RPC patch/repair.

## Not implemented
* Patch download using signed URLS.

### CODE REVIEW

**Comment by goaaats** [comment]
@Soreepeong do you remember if there were any ToDos for this? The description said that "rpc patch/repair" isn't confirmed, does it just need to be tested?

**Comment by Soreepeong** [comment]
Yeah those still aren't tested yet. If it doesn't work then it's probably some stupid reason like a typo, though.

**Comment by reiichi001** [comment]
I want to say I had previously tested those functions on earlier ffxiv versions. 

And I recall asking people to run through them on xlcore too. 

RPC patch would be normal game install operation, correct? I can kick off a fresh install from a debug build to confirm later.

**Comment by Soreepeong** [comment]
`patchinfo` repository's primary branch should be changed to `dt`, or branch names should be changed.

**Comment by reiichi001** [comment]
Repair and install from nothing both tested good on my side. This looks good to merge when we want it.

**Review by goaaats — APPROVED** [review]

**Pull request merged**
