### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by daemitus**
Just going to keep committing to this. I'll try to keep it to comments only to keep it simple.

### CODE REVIEW

**Comment by daemitus** [comment]
Couldn't help myself. Pressed autoformat and cleaned up imports in common.

**Comment by goaaats** [comment]
Just did that a commit ago :/

**Comment by daemitus** [comment]
push it and ill rebase

**Comment by daemitus** [comment]
```
"D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.sln" (Build target) (1) ->
"D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Tests\XIVLauncher.Tests.csproj" (default target) (6) ->
(EnsureNuGetPackageBuildImports target) -> 
  D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Tests\XIVLauncher.Tests.csproj(74,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\MSTest.TestAdapter.2.1.2\build\net45\MSTest.TestAdapter.props.
```

What did I do now :|

**Comment by goaaats** [comment]
Not your fault - also does this on master, not sure why

**Comment by daemitus** [comment]
merge conflicts resolved, up to date with your latest stuff.

**Pull request closed without merging**
