### PR TITLE
Switch OTP: Cancel and Ok buttons.

### PR DESCRIPTION
**Pull request by ccanaday1**
This is for applying to switch the "Cancel" and "OK" button for issue #1155 

Regards
ccanaday1

### CODE REVIEW

**Comment by NotNite** [comment]
Heya - I'm not sure this PR looks correct. This seems to be merging `goatcorp/master` into a bot for Dependabot.

You probably want to remake the PR, from the changes you pushed to your fork of XIVLauncher to the `master` branch here. There should be a neat button for it when you visit your fork on GitHub's web page. If it doesn't appear, make sure you actually pushed your changes to GitHub.

Thank you for the contribution, though, and I'll be happy to review this when you get it sorted out!

**Comment by ccanaday1** [comment]
@NotNite 
Will do! Thankyou for letting me know I am looking into this and I created a fork of the XIVLauncher.

**Comment by ccanaday1** [comment]
@NotNite 
I set my fork and added a branch called OTP_Changes. When goatcorp/master is selected I don't get anything but when I select one of the Dependabot I am able to create a pull request.  I'm not to sure what I am doing wrong.

**Comment by MidoriKami** [comment]
This should probably be closed.

**Pull request closed without merging**
