### PR TITLE
Use Dalamuds new console interface to launch the game

### PR DESCRIPTION
**Pull request by marzent**
This makes use of https://github.com/goatcorp/Dalamud/pull/811 in order to inject Dalamud ~~so that the ACL fix component can be removed from XL~~.

~~To compensate for the use case of an ACL fixed launch without Dalamud, a new `DalamudLoadMethod` is introduced that is currently exposed in xl-core and could, if need be, added to WPF XL as well.~~

This should fix fake login on non-Windows systems on xl-core and https://github.com/goatcorp/FFXIVQuickLauncher/issues/957.

In Addition since only `Process` objects and no PIDs are passed around anymore this should also fix https://github.com/goatcorp/FFXIVQuickLauncher/issues/963, @Aireil would be much appreciated if you could give this a spin ♥

### CODE REVIEW

**Comment by Aireil** [comment]
It started for me, fixing #963, didn't test anything else 👍 .

**Comment by goaaats** [comment]
XL not acl-fixing when Dalamud is disabled isn't really an option for me, because that's how I dev. I honestly believe that it's best to leave it to XL.

**Comment by marzent** [comment]
Just thought it would help with AV targeting XL maybe, could be left in as-is if the launch through Dalamud but no injection mode is not good enough (well and there is still no GUI for that in the WPF version)

**Comment by goaaats** [comment]
We'd have to change our distribution model for dalamud then, because at the moment, it's entirely ignored on patches. It's good to keep this in mind but we should try to fix the original issue first, imo.

**Comment by marzent** [comment]
Ah I see, haven’t thought of that…
Would using the ACL fix on the Windows side of things be enough or should DalamudWineHelper also be put back to launch with fixed ACLs without dalamud

**Review by goaaats — APPROVED** [review]

**Pull request merged**
