### PR TITLE
Fix some boot hash targets not existing anymore

### PR DESCRIPTION
**Pull request by NotNite**
They deleted some of the files we hash for boot so I'm just skipping the ones that don't exist. Also because the last entry isn't guaranteed to exist I moved to TrimEnd for the comma.

### CODE REVIEW

**Comment by NotNite** [comment]
Also: not sure if `i` matters here? This passed boot hash checks but I don't know if it's 100% accurate boot behavior (not that we're doing accurate boot behavior anyways lmao).

**Comment by NotNite** [comment]
Checked by Fiddler'ing boot, it matches current behavior.

**Comment by marzent** [comment]
Wouldn't it be better to adjust https://github.com/goatcorp/FFXIVQuickLauncher/blob/f945283ea795e3ee0910b86b2e663971bd0abeaf/src/XIVLauncher.Common/Game/Launcher.cs#L80

**Comment by NotNite** [comment]
They both have the same result, but I can do that if it's wanted. Gimme a few seconds...

**Review by marzent — APPROVED** [review]
Thanks IMO it is a bit clearer that way

**Review by avafloww — APPROVED** [review]

**Review by Blooym — APPROVED** [review]
Just here to give my grey checkmark

**Pull request merged**
